helm:
  parameters:
  - name: image.name
    value: ghcr.io/hargata/lubelogger
    forcestring: true
  - name: image.tag
    value: v1.5.2
    forcestring: true
  - name: lubelogger.image
    value: ghcr.io/hargata/lubelogger
    forcestring: true
  - name: lubelogger.image.repository
    value: ghcr.io/hargata/lubelogger
    forcestring: true
