helm:
  parameters:
  - name: image.name
    value: quay.io/argoproj/argocd
    forcestring: true
  - name: image.tag
    value: v3.1.6
    forcestring: true
  - name: argo-cd.server.image.repository
    value: quay.io/argoproj/argocd
    forcestring: true
  - name: argo-cd.server.image.tag
    value: v3.1.6
    forcestring: true
