apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: immich
spec:
  project: default
  source:
    repoURL: https://anthonymag.github.io/helm-charts/
    targetRevision: 1.0.0
    helm:
      valueFiles:
        - values.yaml
      parameters:
        - name: immich.controllers.main.containers.main.image.tag
          value: v2.6.3
    chart: immich
  destination:
    server: https://kubernetes.default.svc
    namespace: immich
  syncPolicy:
    syncOptions:
      - CreateNamespace=true

