apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nextcloud
spec:
  project: default
  source:
    repoURL: https://anthonymag.github.io/helm-charts/
    targetRevision: 0.1.1
    helm:
      valueFiles:
        - values.yaml
      parameters:
        - name: nextcloud.image.tag
          value: 32.0.2
    chart: nextcloud
  destination:
    server: https://kubernetes.default.svc
    namespace: nextcloud
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  
