apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nextcloud
spec:
  project: default
  source:
    repoURL: https://anthonymag.github.io/helm-charts/
    targetRevision: 2.1.2
    helm:
      valueFiles:
        - values.yaml
      parameters:
        - name: nextcloud.image.tag
          value: 33.0.3
    chart: nextcloud
  destination:
    server: https://kubernetes.default.svc
    namespace: nextcloud

